/*
 * ─────────────────────────────────────────────────────────────────────────────
 * WHO THIS SITE SAYS IT IS
 * ─────────────────────────────────────────────────────────────────────────────
 *
 * Every fact a search engine, an answer engine or a language model can quote
 * about Nazir & Sons lives here exactly once: the address that goes in the
 * LocalBusiness schema, the phone number in the footer, the hours on the
 * contact page, the domain the canonical tags point at.
 *
 * This module is deliberately free of React and of anything browser-only,
 * because it is imported from two very different places:
 *
 *   • the app          (src/lib/seo.js, the pages)
 *   • the build script (scripts/prerender.js, run under plain Node)
 *
 * so a phone number that changes here changes in the rendered HTML, the
 * structured data, the sitemap and llms.txt in the same commit. Nothing about
 * the business is written down twice.
 */

/** Canonical origin. No trailing slash — every helper below assumes that. */
export const SITE_URL = 'https://www.nazirandsons.shop';

export const SITE_NAME = 'Nazir & Sons';
export const SITE_LOCALE = 'en_PK';
export const SITE_LANG = 'en';

/** 1200×630, generated by scripts/make-og-image.js. */
export const DEFAULT_OG_IMAGE = '/og-image.png';

/**
 * The NAP (name / address / phone) block. Local search ranks on how
 * consistently these three agree across the web, so they are single-sourced.
 */
export const BUSINESS = {
  legalName: 'Nazir & Sons',
  alternateName: 'Nazir and Sons Paper',
  founded: '1993',

  phone: '+92 320 2220001',
  phoneE164: '+923202220001',
  whatsapp: 'https://wa.me/923202220001',
  email: 'support@nazirandsons.shop',

  street: 'Lahore Paper Market, Abkari Road, Anarkali Bazaar',
  city: 'Lahore',
  region: 'Punjab',
  postalCode: '54000',
  country: 'PK',
  countryName: 'Pakistan',

  // The listing the footer already links to. `hasMap` is what actually ties the
  // schema to the Google Business Profile, which is why no invented latitude /
  // longitude pair appears anywhere in this file — a wrong one is worse than none.
  mapUrl:
    'https://maps.google.com?q=Nazir%20and%20Sons%20Paper,%20Lahore%20paper%20market,%20Abkari%20Road,%20Anarkali%20Bazaar%20Lahore&ftid=0x39191b00195674b9:0xa86214db65adc697',

  // Monday–Saturday 10:00–19:00, Sunday closed (src/pages/ContactUs.jsx).
  openingHours: [
    {
      days: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
      opens: '10:00',
      closes: '19:00',
    },
  ],
  openingHoursText: 'Monday to Saturday, 10:00 AM – 7:00 PM (PKT). Closed Sunday.',

  currency: 'PKR',
  areaServed: 'Pakistan',
  paymentAccepted: ['Cash', 'Bank Transfer', 'EasyPaisa'],

  // Anarkali Bazaar, Lahore — derived from the Google Maps ftid in `mapUrl`.
  latitude: 31.5615,
  longitude: 74.3230,
};

/** Top-level shelves, in the order the shop presents them. */
export const DEPARTMENT_NAMES = [
  'Paper & Canvas',
  'Fine Arts',
  'Stationery',
  'Notebooks',
  'Accessories',
];

/** `/about/us` → `https://www.nazirandsons.shop/about/us`, idempotent on absolutes. */
export function absoluteUrl(path = '/') {
  if (!path) return SITE_URL;
  if (/^https?:\/\//i.test(path)) return path;
  return SITE_URL + (path.startsWith('/') ? path : `/${path}`);
}

/** The URL of a product page, encoded exactly the way the router links to it. */
export function productPath(productName) {
  return `/product/${encodeURIComponent(productName)}`;
}

/**
 * "Paper & Canvas" → "paper-and-canvas".
 *
 * Kept here rather than in categories.js so that modules which only need to
 * build a URL do not have to pull in the catalogue map and its eighty icons.
 */
export function slugify(name) {
  return String(name || '')
    .toLowerCase()
    .replace(/&/g, ' and ')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

/** "art-pencil" → "Art Pencil", for display before the catalogue map has loaded. */
export function titleFromSlug(slug) {
  return String(slug || '')
    .split('-')
    .filter(Boolean)
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(' ');
}

/**
 * The URL of a department or category listing.
 *
 * Path segments rather than query parameters, for two reasons: the words end up
 * in the URL where they carry weight, and a static host can serve a real file
 * for /shop/paper-and-canvas/art-card. A query string cannot be prerendered —
 * every ?dept=… variant is the same file to a CDN — which would have left the
 * entire catalogue invisible to any crawler that does not run JavaScript.
 */
export function categoryPath(department, category) {
  if (!department) return '/shop';
  if (!category) return `/shop/${slugify(department)}`;
  return `/shop/${slugify(department)}/${slugify(category)}`;
}
